apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15 #nginx:1.15

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
spec:
  type: LoadBalancer #create classic load balancer by default
  selector:
    tier: frontend
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80