apiVersion: v1
kind: ServiceAccount
metadata:
  name:
  annotations:
#  eks.amazonaws.com/role-arn: arn:aws:iam::633788536644:role/oidc-test #i need to create mine to gain access into the image
  eks.amazonaws.com/role-arn: arn:aws:iam::878756956432:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/180BE925FE694537E50089BFB41BA03
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test2
---
apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  serviceAccountName: test1
  containers:
  - name: debug
    image: rkalluru/loaded:centos8
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  serviceAccountName: test2
  containers:
  - name: debug
    image: rkalluru/loaded:centos8

